### ISSUE TITLE
[Bug] Replay the song when returning to the program interface by using rofi.

### ISSUE THREAD

**Issue by axionl** [Taiko2k/tauonmb#11] opened 2018-08-31 14:52 UTC
**Desc:**

- When using `Rofi` as the task switcher to open the window of `tauonmb`, the music will be replayed from start.
- The `plasma compositing` will be blocked when using it, so I disable the `applications to block compositing` options on the system setting.

**Env:**
- ArchLinux Latest
- Plasma 5.13.4-1 
- Kde-applications 18.08.0-1
- Plasma-framework 5.49.0-1

**URL:**
- [Rofi](https://github.com/DaveDavenport/rofi): A window switcher, application launcher and dmenu replacement

**Comment by Taiko2k** [comment] 2018-08-31 15:31
I can replicate this. What I believe is happening is as you press the <kbd>Enter</kbd>, the window is receiving that input too for some reason. I'm not sure if this is intended behaviour from Rofi, but I've fixed this in Tauon now by ignoring the Enter key if the window is being focused.

This fix will be available in the next release. 

That was the issue?

**Comment by axionl** [comment] 2018-08-31 16:06
Well, and I found another problem, the `TypeError` will crash the main application.
It will happen when `scrolling` the playlist, sometimes.

```python
Traceback (most recent call last):
File "tauon.py", line 21050, in <module>
artist_info_box.draw(gui.playlist_left, gui.panelY, gui.plw, gui.artist_panel_height)
File "tauon.py", line 17717, in draw
ddt.draw_text((x + round(215 * gui.scale), y + 14 * gui.scale, 4, text_max_w, 4000), self.processed_text, [230, 230, 230, 255], 14, bg=backgound, range_height=h - 26, range_top=self.scroll_y)
File "/opt/tauon-music-box/t_draw.py", line 291, in draw_text
range_top=range_top, range_height=range_height)
File "/opt/tauon-music-box/t_draw.py", line 256, in __draw_text_cairo
self.__render_text(self.ttc[key], x, y, range_top, range_height, align)
File "/opt/tauon-music-box/t_draw.py", line 153, in __render_text
self.source_rect.h = range_height
TypeError: int expected instead of float
```

**Comment by Taiko2k** [comment] 2018-08-31 23:59
Ok that will be fixed. I assume you were using the UI scaling option?

**Comment by Taiko2k** [comment] 2018-09-01 04:39
Yes I haven't tested the scaling as much, so its a bit more unstable. 

Ill close this now, feel free to report any more issues you come across.

**Closed by Taiko2k** 2018-09-01 04:39 UTC
